---
  - name: check if disks support SMART
    shell: "smartctl -s on {{ item }} ; smartctl -i {{ item }} | grep -qc 'SMART support is: Enabled'"
    with_items: "{{ ansible_devices }}"
    register: smart_enabled_stdout
    ignore_errors: true
  
  - name: init fact for smart_enabled devices
    set_fact:
      smart_enabled_devices: "{{ [] }}"

  - name: add devices to fact smart_enabled devices
    set_fact: 
      smart_enabled_devices: "{{ smart_enabled_devices + [ item.item | from_yaml ] }}"
    with_items: "{{ smart_enabled_stdout.results }}"
    when: item.rc == 0

  - name: "Execute smart test"
    shell: "smartctl -X /dev/{{ item }}"
    with_items: "{{ smart_enabled_devices }}"
    when: smartctl_test_type is defined and (smartctl_test_type == 'long' or smartctl_test_type == 'short')
    ignore_errors: true

  - name: "Execute smart test"
    shell: "smartctl -t {{ smartctl_test_type }} /dev/{{ item }}"
    with_items: "{{ smart_enabled_devices }}"
    when: smartctl_test_type is defined and (smartctl_test_type == 'long' or smartctl_test_type == 'short')

  - name: "Wait for smart test end" 
    shell: "smartctl -a /dev/{{ item }} | grep 'progress' -i -A 1"
    register: result
    until: result.rc == 0 and result.stdout.find("progress") == -1 or result.rc != 0
    ignore_errors: true
    retries: 1000
    delay: 60
    when: smartctl_test_type is defined and (smartctl_test_type == 'long' or smartctl_test_type == 'short')
    with_items: "{{ smart_enabled_devices }}"

  - name: "Install pyyaml"
    pip:
      name: "pyyaml"

  - name: "Install pySMART"
    pip:
      name: "pySMART"

  - name: "Create tempfile for smartctl_reports.py"
    shell: "mktemp -t"
    register: tempfile

  - name: "Copy smartctl_reports.py"
    copy:
      src: smartctl_reports.py
      dest: "{{ tempfile.stdout }}"

  - name: "Get Results of SMART Selftest"
    shell: "python '{{ tempfile.stdout }}' /dev/{{ item }}"
    register: smartctl_report_stdout
    with_items: "{{ smart_enabled_devices }}"

  - name: "Remove tempfile for smartctl_report.py"
    file:
      path: "{{ tempfile.stdout }}"
      state: absent

  - name: "Set fact smartctl_reports from stdout of smart_report python script"
    set_fact:
      smartctl_reports: "{{ smartctl_reports | default([]) + [ item.stdout | from_yaml ] }}"
    with_items: "{{ smartctl_report_stdout.results }}"
